export const SearchActionTypes = {
  FETCH_AUTOCOMPLETE_OPTIONS_SUCCESS: "FETCH_AUTOCOMPLETE_OPTIONS_SUCCESS",
  FETCH_AUTOCOMPLETE_START: "FETCH_AUTOCOMPLETE_START",
  FETCH_AUTOCOMPLETE_FAILED: "FETCH_AUTOCOMPLETE_FAILED",
  CLEAR_AUTOCOMPLETE_OPTIONS: "CLEAR_AUTOCOMPLETE_OPTIONS",
};
