export const MoviesActionTypes = {
  //all movies
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MORE_MOVIES_START: "FETCH_MORE_MOVIES_START",
  FETCH_MOVIES_INITIAL: "FETCH_MOVIES_INITIAL",
  FETCH_MORE_MOVIES: "FETCH_MORE_MOVIES",
  FETCH_MOVIES_FAILED: "FETCH_MOVIES_FAILED",
  //movie details
  FETCH_MOVIE_DETAILS_START: "FETCH_MOVIE_DETAILS_START",
  FETCH_MOVIE_DETAILS_SUCCESS: "FETCH_MOVIE_DETAILS_SUCCESS",
  FETCH_MOVIE_DETAILS_FAILED: "FETCH_MOVIE_DETAILS_FAILED",
};
