export const UserActionTypes = {
  GET_FAVORITE_MOVIES: "GET_FAVORITE_MOVIES",
  ADD_MOVIE_TO_FAVORITES: "ADD_MOVIE_TO_FAVORITES",
  REMOVE_MOVIE_FROM_FAVORITES: "REMOVE_MOVIE_FROM_FAVORITES",
  USER_ACTION_START: "USER_ACTION_START",
  USER_ACTION_FAILED: "USER_ACTION_FAILED",
};
